version: "3"

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/testRuslan
    volumes:
      - .:/var/www/testRuslan
      - ./back.sh:/back.sh
    environment:
      - TZ=Europe/Moscow
      - XDEBUG_SESSION=1
      - PHP_IDE_CONFIG=serverName=testRuslan.local
    depends_on:
      - db
    networks:
      - web
    tty: true

  db:
    image: mysql:5.6.51
    environment:
      - MYSQL_DATABASE=ruslan
      - MYSQL_USER=ruslan
      - MYSQL_PASSWORD=111
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - db_mysql:/var/lib/mysql
    networks:
      - web

  web:
    image: nginx
    volumes:
      - ./nginx/testRuslan.conf:/etc/nginx/conf.d/default.conf:ro
      - ./log/nginx:/var/log/nginx
      - .:/var/www/testRuslan
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - web

volumes:
  db_mysql:

networks:
  web:
